import { v4 as uuid } from "uuid";

/**
 * Category Database can be added here.
 * You can add category of your wish with different attributes
 * */

// export const categories = [
//   {
//     _id: uuid(),
//     categoryName: "fiction",
//     description:
//       "literature in the form of prose, especially novels, that describes imaginary events and people",
//   },
//   {
//     _id: uuid(),
//     categoryName: "non-fiction",
//     description:
//       "Non-fiction is writing that gives information or describes real events, rather than telling a story.",
//   },
//   {
//     _id: uuid(),
//     categoryName: "horror",
//     description:
//       "Meant to cause discomfort and fear for both the character and readers, horror writers often make use of supernatural and paranormal elements in morbid stories that are sometimes a little too realistic.",
//   },
// ];

export const categories = [
    {   
      _id: uuid(),
      id:1,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq29zM4sZ-T8wWl6usxGEUJ7WGgi76uCrsuA&usqp=CAU",
      title:"Healthcare Devices",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. one",
      brandfilters: ["Johnson & Johnson" ,
                      "Novartis AG",
                      "Abbott Laboratories",
                      "Medtronic PLC",
                      "Baxter International",
                      "Danaher Corporation",
                      "General Electric",
                      "3M Company",
                      "Siemens Healthineers",
                      "Stryker Corporation",
                      "Omron",
                      "Dr Trust",
                      "Hoffen",
                      "Dr Morepen"
                  ],
      productTags:[
          "BP monitors",
          "Weighing Scales",
          "Glucometers",
          "Excercise equipments",
          "Pulse oximeter",
          "Vital Signs monitors & wearables",
          "Thermometers",
          "Body Massager",
          "Nebulizers & Vaporizers",
          "Mobility Equipments",
          "Supports & Braces"
      ]
     
  },
  {   
      _id: uuid(),
      id:2,
      img:"https://www.choosetolivebetter.com/sites/default/files/eating-drinking-final_0.png",
      title:"Health Food and Drinks",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters: ["Boost by Unilever",
                      "Horlicks",
                      "Bournvita by Cadbury",
                      "Complan",
                      "Powervita by Patanjali",
                      "PediaSure by Abbott Laboratories",
                      "Ensure",
                      "Protinex"
                  ],
      productTags:["Weight Gain", "Weight Loss", "Energy drink"]
  },
  {   
      _id: uuid(),
      id:3,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8MESVejz1iRQmGH6c6GPlyXWVIvW7JZYBGw&usqp=CAU",
      title:"Personal Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters: ["VLCC",
                      "Loreal",
                      "Amway",
                      "Kaya skin", 
                      "Lakme", 
                      "Richfeel", 
                      "Lotus Herbal",
                      "Hindustan Unilever"
                  ],
      productTags:["Body lotions", 
                  "hair dyes", 
                  "cosmetics", 
                  "creams", 
                  "deodorants", 
                  "bath soaps", 
                  "dental care products",
                  "shampoos",
                  "toothpaste",
                  "perfumes", 
                  "UV filters", 
                  "detergents",
                  "sunscreens",
                  ]
  },
  {   
      _id: uuid(),
      id:4,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV1szF8AlO1frM0h0ccv_P8Gz6qcu_ZSUwtw&usqp=CAU",
      title:"Ayurvedic Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters: ["Dabur India Ltd.",
                      "Patanjali Ayurveda",
                      "Baidyanath",
                      "Hamdard Labs",
                      "Zandu Ayurveda",
                      "Himalaya wellness",
                      "vicco Labs"
                  ],
      productTags:["Pain relief", 
                  "Hair care",
                  "Skin Care",
                  "Digestive Care",
                  "Liver Health",
                  "cold n cough",
                  "Diabetes Care",
                  "Cholestrol control",
                  "Respiratory relief",
              ]
  },
  {   img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ65XbvKpRNM3EGa5eD-fJZ0g1SuX-vB1UZAw&usqp=CAU",
      title:"Mother and Baby Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters: ["Himalaya Baby Product",
                      "Chicco Baby Products",
                      "MamaEarth Baby Products",
                      "Sebamed Baby Products",
                      "Aveeno Baby Products",
                      "Dove Baby Products",
                      "Pigeon Baby Products",
                      "Patanjali Baby Products"
                  ],
      productTags:["Baby Wash",
          "Soap",
          "Powder",
          "Oil",
          "Haircare",
          "Cream",
          "Lotion",
          "Wipes",
          "Gift Packs",
          "Nappy Pads",
          "Cotton Buds",
          "Toothbrush",
          "Shampoo" ]
  },
  {   
      _id: uuid(),
      id:5,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZMwm6TBBFCUDrNGVwVYwkF-unbjvf4RgAbw&usqp=CAU",
      title:"Skin Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters: [
          "L'Oréal",
          "Gillette",
          "Nivea",
          "Estée Lauder",
          "Clinique",
          "Guerlain",
          "Shiseido",
          "Garnier"
      ],
      productTags:[ "Dryness",
          "Acne Treatment",
          "Tan Removal",
          "Dark Circles",
          "Sun Protection",
          "Prevention & Protection",
          "Make Up Remover",
          "Anti-Aging",
          "Uneven Skin Tone",
          "Pigmentation",
          "Pore Tightening",
          "Lightening And Brightening",
          "Oil Control"
      ]
  },
  {   
      _id: uuid(),
      id:6,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFYoE82xIpzqwAcxdajyBPDq3mJeLSAU4JFg&usqp=CAU",
      title:"Diabetic Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Novo Nordisk A/S",
              "Ypsomed AG",
              "Abbott Laboratories",
              "Ascensia Diabetes Care Holdings AG",
              "Hoffmann-La Roche Ltd.",
              "Johnson & Johnson",
              "Medtronic PLC",
              "Becton, Dickinson and Company",
              "Terumo Corporation",
              "Sanofi",
              "Acc check"
          ],
      productTags:["Short-acting insulin",
          "Rapid-acting insulins",
          "Intermediate-acting insulin",
          "Long-acting insulins",
          "Combination insulins",
          "Amylinomimetic drug",
          "Alpha-glucosidase inhibitors",
          "Biguanides",
         " Dopamine agonist",
          "Dipeptidyl peptidase-4 (DPP-4) inhibitors",
          "Glucagon-like peptide-1 receptor agonists (GLP-1 receptor agonists)",
          "Meglitinides",
          "Sodium-glucose transporter (SGLT) 2 inhibitors",
          "Sulfonylureas",
          "Thiazolidinediones"]
  },
  {   
      _id: uuid(),
      id:7,
      img:"https://preview.pixlr.com/images/800wm/1503/1/1503120701.jpg",
      title:"Health Condition",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Johnson & Johnson",
                      "Novartis",
                      "Abbott Laboratories",
                      "Medtronic",
                      "Baxter",
                      "glenamrk",
                      "Lispro",
                      "Cipla",
                      "Sun pharma"
                  ],
      productTags: ["Cancer",
          "Cholesterol",
          "Health Care Associated Infection Reporting",
          "High Blood Pressure",
          "HIV/AIDS Counseling & Testing Sites",
          "Hyperthermia",
          "Hypothermia",
          "Missouri Million Hearts",
          "Obesity",
          "STDs",
          "Time Critical Diagnosis System (Stroke and STEMI)",
          "Traumatic Brain Injury"]
  },
  {   
      _id: uuid(),
      id:8,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdXeHNGAKmYpglS8Z2jkvlvkBaonpxIOXloQ&usqp=CAU",
      title:"Home Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Hindustan unilever",
                  "Godrej",
                  "Nirma",
                  "Procter & Gamble",
                  "Reckitt Benckiser"    
          ],
      productTags: ["Laundry detergents (powder, liquid and tablet)",
          "Fabric conditioners",
          "Dishwashing detergents (liquid and tablet)",
         " Hard floor and surface cleaners",
          "Carpet cleaners",
          "Oven cleaners",
          "Air fresheners"]
  },
  {   img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1jzzTKtx1E-gr2g4ci-qHkforVpf8kc-Ogw&usqp=CAU",
      title:"Fitness Supplements",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Muscle Blaze",
                  "Endura Mass",
                  "Prontinex",
                  "Procter & Gamble",
                  "Reckitt Benckiser",
                  "Muscle Mass",
                  "Whey",
                  "Truebasics",
                  "1MG",    
          ],
      productTags: ["Weight gain", "weight Loss"]
  },
  {   
      _id: uuid(),
      id:9,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNJH3TDSrSNaG9kAaH24CgbmUbjUejeWh_fw&usqp=CAU",
      title:"Elderly Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Tenura","step Neuro","NRS HealthCare", "Elder ease", "Trionic"],
      productTags: ["Shower Chair with Backrest",
          "Portable Conversion Commode",
          "Toilet Squat Stool",
          "Wall-Mounted Indian Conversion Commode",
          "Folding Commode Chair with Castors",
          "Stainless Steel Grab Bars",
          "Air Pump Mattress for Bed Sores",
          "Bedside Rail"]
  },
  {   
      _id: uuid(),
      id:10,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNT3ozmvVdMCtsL8kgt-1vSjukFvJ8xHID7w&usqp=CAU",
      title:"Surgicals and Dressings",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Bactigras Dressing","Ent dressings","NRS HealthCare"],
      productTags:["Collagen Film Dressing",
          "Gelatin Sponge Porcine Origin",
          "Sterile Porous Collagen Dressing Sheet",
          "Hospital Dressing Trolley",
          "Surgical Isolation Gown",
          "N95 Mask",
          "Collagen Burn Sheet",
          "Hycoloid Hydrocolloid Wound Dressing"]
  },
  {   
      _id: uuid(),
      id:11,
      img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSavKV4sOSdmA5_Qqt8k8wGBVeclUGSr0rFlw&usqp=CAU",
      title:"Pet Care",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      brandfilters:["Canponus wet wipes pvt ltd","Paws India","Pet Vanity", "Liveath BioPharma"],
      productTags:["PetHex Anti Bacterial and Anti Fungal Shampoo for Dogs",
          "Petcare Notix Green Shampoo",
          "Petcare Proviboost Syrup",
          "Pet Joint Supplement for Dogs",
          "Petcare Livoferol Pet Supplement",
          "Petcare Seledruff Shampoo",
          "Petcare Notix Scrub-Liquid Shampoo for Dogs",
          "Pet food"
      ]
  },
  {   
    _id: uuid(),
    id:12,
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSavKV4sOSdmA5_Qqt8k8wGBVeclUGSr0rFlw&usqp=CAU",
    title:"Fitness & Supplements",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    brandfilters:["Canponus wet wipes pvt ltd","Paws India","Pet Vanity", "Liveath BioPharma"],
    productTags:["PetHex Anti Bacterial and Anti Fungal Shampoo for Dogs",
        "Petcare Notix Green Shampoo",
        "Petcare Proviboost Syrup",
        "Pet Joint Supplement for Dogs",
        "Petcare Livoferol Pet Supplement",
        "Petcare Seledruff Shampoo",
        "Petcare Notix Scrub-Liquid Shampoo for Dogs",
        "Pet food"
    ]
},
]
 